Repository keypang/SWE-YutGame, pull requests merged in 2025-04, with the labels that each got.

#2 [#1]Feat:게임 설정 컨트롤러 및 게임 설정 화면(SWING) 기본 설계
  SWE-YUT/.gitignore
  SWE-YUT/.idea/.gitignore
  SWE-YUT/.idea/misc.xml
  SWE-YUT/.idea/modules.xml
  SWE-YUT/.idea/vcs.xml
  SWE-YUT/SWE-YUT.iml
  SWE-YUT/src/Main.java
  SWE-YUT/src/controller/StartScreenController.java
  SWE-YUT/src/model/BoardType.java
  SWE-YUT/src/model/Model.java
  SWE-YUT/src/model/StartInfo.java
  SWE-YUT/src/view/GameView.java
  SWE-YUT/src/view/SwingView.java
Labels: PSJ

#6 [#3]Feat: MODEL 기본 구성 구현 및 CONTROLLER 초기화면 연동
  .idea/.gitignore
  .idea/libraries/junit_jupiter.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  SWE-YUT/src/Main.java
  SWE-YUT/src/controller/GameScreenController.java
  SWE-YUT/src/controller/StartScreenController.java
  SWE-YUT/src/model/Board.java
  SWE-YUT/src/model/Cell.java
  SWE-YUT/src/model/GameManager.java
  SWE-YUT/src/model/Piece.java
  SWE-YUT/src/model/Player.java
  SWE-YUT/src/model/Yut.java
  SWE-YUT/test/controller/YutThrowTest.java
  SWE-YUT/test/model/YutThrowTest1.java
  SWE-YutGame.iml
  out/production/SWE-YutGame/view/images/사각형.png
  out/production/SWE-YutGame/view/images/오각형.png
  out/production/SWE-YutGame/view/images/육각형.png
  out/production/SWE-YutGame/view/images/턴화살표.png
  out/production/SWE-YutGame/view/images/플레이어1말.png
  out/production/SWE-YutGame/view/images/플레이어2말.png
  out/production/SWE-YutGame/view/images/플레이어3말.png
  out/production/SWE-YutGame/view/images/플레이어4말.png
Labels: LSE, FEAT

#9 [Refactor] 디렉토리 정리
  .gitignore
  SWE-YUT/.gitignore
  SWE-YUT/.idea/.gitignore
  SWE-YUT/.idea/misc.xml
  SWE-YUT/.idea/modules.xml
  SWE-YUT/.idea/vcs.xml
  SWE-YUT/SWE-YUT.iml
  SWE-YutGame.iml
  src/Main.java
  src/controller/GameScreenController.java
  src/controller/StartScreenController.java
  src/model/Board.java
  src/model/BoardType.java
  src/model/Cell.java
  src/model/GameManager.java
  src/model/Piece.java
  src/model/Player.java
  src/model/StartInfo.java
  src/model/Yut.java
  src/view/GameView.java
  src/view/SwingPlayScreen.java
  src/view/SwingView.java
  src/view/images/사각형.png
  src/view/images/오각형.png
  src/view/images/육각형.png
  src/view/images/턴화살표.png
  src/view/images/플레이어1말.png
  src/view/images/플레이어2말.png
  src/view/images/플레이어3말.png
  src/view/images/플레이어4말.png
  test/controller/YutThrowTest.java
  test/model/YutThrowTest1.java
Labels: JYC, REFACTOR

#12 [REFECTOR] 윷 로직 수정 및 GAMEMANAGER 코드 수정 #11
  src/controller/GameScreenController.java
  src/model/GameManager.java
  src/model/StartInfo.java
  src/model/Yut.java
  src/model/YutResult.java
  test/controller/YutThrowTest.java
  test/model/YutThrowTest1.java
Labels: LSE, REFACTOR

#17 [FEAT][REFACTOR] 메인 게임화면 윷 던지기 버튼 기능 추가 및 뷰 관련 클래스 이름 변경 / 뷰-컨트롤러 연동 테스트
  .idea/misc.xml
  src/Main.java
  src/controller/GameScreenController.java
  src/controller/StartScreenController.java
  src/model/YutResult.java
  src/view/GameConfigView.java
  src/view/GamePlayView.java
  src/view/SwingConfigScreen.java
  src/view/SwingPlayScreen.java
  test/controller/YutThrowTest.java
Labels: PSJ, FEAT, REFACTOR

#18 [Feat] 게임 전체 데이터 전달 구현
  .idea/.gitignore
  .idea/libraries/junit_jupiter.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  SWE-YutGame.iml
  out/production/SWE-YutGame/view/images/사각형.png
  out/production/SWE-YutGame/view/images/오각형.png
  out/production/SWE-YutGame/view/images/육각형.png
  out/production/SWE-YutGame/view/images/턴화살표.png
  out/production/SWE-YutGame/view/images/플레이어1말.png
  out/production/SWE-YutGame/view/images/플레이어2말.png
  out/production/SWE-YutGame/view/images/플레이어3말.png
  out/production/SWE-YutGame/view/images/플레이어4말.png
  pom.xml
  src/controller/StartScreenController.java
  src/model/Board.java
  src/model/GameManager.java
  src/model/Player.java
  src/model/PositionDTO.java
  src/model/StartInfo.java
  test/model/GameManagerTest.java
  test/model/YutThrowTest1.java
Labels: JYC, FEAT

#19 [Feat] 말 이동
  SWE-YUT/.idea/misc.xml
  SWE-YUT/.idea/vcs.xml
  SWE-YUT/src/Main.java
  src/model/Board.java
  src/model/Cell.java
  src/model/Piece.java
  src/model/Player.java
Labels: PSY, FEAT

#21 [Fix] 오류 폴더 삭제
  SWE-YUT/.idea/misc.xml
  SWE-YUT/.idea/vcs.xml
  SWE-YUT/src/Main.java
Labels: PSY, FIX

#23 [#22][FEAT][REFACTOR][CHORE] 윷 결과 이미지 디자인 / pom.xml 파일 수정 / GameManger 오타 수정
  pom.xml
  src/model/GameManager.java
  src/view/SwingPlayScreen.java
  src/view/images/개.png
  src/view/images/걸.png
  src/view/images/도.png
  src/view/images/모.png
  src/view/images/빽도.png
  src/view/images/윷.png
Labels: PSJ, FEAT, REFACTOR, CHORE

#25 [#24][FEAT][UI] 말판 이미지 개선 / 업힌 말 이미지 추가 / 지정 윷 던지기 코드 추가(Only View)
  .classpath
  .project
  .settings/org.eclipse.jdt.core.prefs
  src/view/SelectYutResultScreen.java
  src/view/SwingPlayScreen.java
  src/view/images/사각형.png
  src/view/images/오각형.png
  src/view/images/육각형.png
  src/view/images/플레이어1말2겹.png
  src/view/images/플레이어1말3겹.png
  src/view/images/플레이어2말2겹.png
  src/view/images/플레이어2말3겹.png
  src/view/images/플레이어3말2겹.png
  src/view/images/플레이어3말3겹.png
  src/view/images/플레이어4말2겹.png
  src/view/images/플레이어4말3겹.png
Labels: KHS, FEAT, UI

#29 [Feat] 이동 가능 지점 전달 구현
  SWE-YutGame.iml
  src/model/Board.java
  src/model/GameManager.java
  test/controller/YutThrowTest.java
  test/model/GameManagerTest.java
Labels: JYC, FEAT
