Repository keypang/SWE-YutGame, pull requests merged in 2025-05, with the labels that each got.

#32 [FEAT] 말 동시 이동 구현
  src/Main.java
  src/model/Board.java
  src/model/Piece.java
Labels: PSY, FEAT

#34 [#33][FEAT][REFACTOR] 게임 화면 최적화 / 윷 결과 리스트 반환 / 게임 종료 화면 구현
  src/controller/GameScreenController.java
  src/model/GameManager.java
  src/view/GamePlayView.java
  src/view/SelectYutResultScreen.java
  src/view/SwingPlayScreen.java
Labels: PSJ, FEAT, UI, REFACTOR

#38 [TEST] Model JUnit 테스트
  src/model/Board.java
  test/model/BoardTest.java
Labels: PSY, TEST

#40 [FEAT] [UI] 말 꺼내기 선택하기 이동가능점 표시 메서드 및 UI 구현
  src/controller/GameScreenController.java
  src/model/PositionDTO.java
  src/view/GamePlayView.java
  src/view/SwingPlayScreen.java
  src/view/images/이동가능점.png
Labels: KHS, FEAT, UI

#45 [Refactor] 말 선택 및 이동가능점 코드 구조 변경
  src/view/GamePlayView.java
  src/view/SwingPlayScreen.java
Labels: KHS, REFACTOR

#56 FIX: 완주 처리 오류 수정
  src/model/Board.java
  test/model/BoardTest.java
Labels: PSY, FIX

#60 FIX: 미출발 Piece 백도 오류 수정
  src/model/Board.java
Labels: PSY, FIX

#63 [#62][UI] 오각형 윷판에 대한 좌표 매핑 추가
  src/view/SwingPlayScreen.java
Labels: PSJ, FEAT, UI

#67 Feat: 규칙에 맞는 지름길 로직
  src/model/Board.java
  src/model/Cell.java
  src/model/Piece.java
  test/model/BoardTest.java
Labels: PSY, FEAT

#70 FIX: 실제 이동 오류 수정
  src/model/Board.java
  test/model/BoardTest.java
Labels: PSY, FIX

#72 [FEAT] [UI] 오각형 육각형 연결 UI 구현
  src/view/SwingPlayScreen.java
  src/view/images/이동가능점오각형.png
  src/view/images/이동가능점육각형.png
Labels: KHS, FEAT, UI

#81 [FEAT] [UI] 완주셀(F) 추가 및 윷 선택 메서드 추가
  src/view/SelectYutResultScreen.java
  src/view/SwingPlayScreen.java
  src/view/images/완주셀.png
  src/view/images/이동가능점오각형.png
Labels: KHS, FEAT, UI

#88 [#87][REFACOTR] 코드 컨벤션 적용
  src/controller/GameScreenController.java
  src/controller/StartScreenController.java
  src/model/Board.java
  src/model/BoardType.java
  src/model/Cell.java
  src/model/GameManager.java
  src/model/Piece.java
  src/model/Player.java
  src/model/PositionDTO.java
  src/model/StartInfo.java
  src/model/Yut.java
  src/model/YutResult.java
  src/view/GameConfigView.java
  src/view/GamePlayView.java
  src/view/SelectYutResultScreen.java
  src/view/SwingConfigScreen.java
  src/view/SwingPlayScreen.java
  test/model/GameManagerTest.java
Labels: PSJ, REFACTOR

#90 [REFACTOR] 불필요한 IMPORT 삭제
  src/model/Yut.java
  src/view/GamePlayView.java
  src/view/SelectYutResultScreen.java
  src/view/SwingPlayScreen.java
Labels: PSJ, REFACTOR

#92 [FIX][UI] 화면에서 말이 최대 4개까지 업힐 수 있도록 수정
  src/view/SwingPlayScreen.java
Labels: PSJ, UI, FIX

#94 [FEAT] [UI] 새 Dialog 메세지 추가 및 기존 오류 수정
  src/view/SelectYutResultScreen.java
  src/view/SwingPlayScreen.java
Labels: KHS, FEAT, UI, FIX

#96 [DOCS] 구현 메소드에 대한 설명 작성
  META-INF/MANIFEST.MF
  src/model/GameManager.java
Labels: JYC, DOCS

#99 [BUILD] pom.xml 에 javafx 관련 의존성 추가
  pom.xml
  src/main/java/JavaFxMain.java
Labels: PSJ, UI

#100 [FEAT] javaFx 게임 설정화면 구성
  pom.xml
  src/JavaFxMain.java
  src/main/java/JavaFxMain.java
  src/view/JavaFxConfigScreen.java
Labels: PSJ, FEAT, UI

#102 [#101] JavaFx UI 메인화면 추가 및 이미지 파일 추가
  src/JavaFxMain.java
  src/view/JavaFxConfigScreen.java
  src/view/JavaFxPlayScreen.java
  src/view/JavaFxSelectYutResultScreen.java
  src/view/SelectYutResultScreen.java
  src/view/SwingPlayScreen.java
  src/view/images/HEXAGON.png
  src/view/images/PENTAGON.png
  src/view/images/SQUARE.png
  src/view/images/finishCell.png
  src/view/images/turnArrow.png
Labels: KHS, FEAT, UI

#105 [#104][FEAT] javafx UI 와 컨트롤러 연결
  src/JavaFxMain.java
  src/controller/StartScreenController.java
  src/view/JavaFxConfigScreen.java
Labels: PSJ, FEAT, UI

#107 [#106][FEAT][UI] javaFx 버전 게임플레이 화면 구현 완료(사각형)
  src/view/JavaFxPlayScreen.java
Labels: PSJ, FEAT, UI

#109 [FEAT] [UI] 오각형, 육각형 좌표 구현 및 이미지 로드 코드 추가
  src/view/JavaFxPlayScreen.java
  src/view/JavaFxSelectYutResultScreen.java
Labels: KHS, FEAT, UI

#114 [#112][CHORE] VIEW 코드 주석추가
  src/JavaFxMain.java
  src/Main.java
  src/controller/GameScreenController.java
  src/controller/StartScreenController.java
  src/view/GameConfigView.java
  src/view/GamePlayView.java
  src/view/JavaFxSelectYutResultScreen.java
  src/view/global/GameConfigView.java
  src/view/global/GamePlayView.java
  src/view/javafx/JavaFxConfigScreen.java
  src/view/javafx/JavaFxPlayScreen.java
  src/view/javafx/JavaFxSelectYutResultScreen.java
  src/view/swing/SelectYutResultScreen.java
  src/view/swing/SwingConfigScreen.java
  src/view/swing/SwingPlayScreen.java
  test/controller/YutThrowTest.java
Labels: PSJ, CHORE
